[package]
name = "website-api-tester"
version = "0.1.0"
authors = ["Michael Lodder <redmike7@gmail.com>"]
edition = "2018"

[dependencies]
base64-url = "1.1"
bs58 = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.8"
sodiumoxide = "0.2"
structopt = "0.3"
